/**
 * Itens da lista de serviços da LC 116/2003 mais usados no comércio/serviços de varejo (lista resumida para seleção).
 * Itens usados nos serviços cadastrados são acrescentados à lista na tela. Confirme o enquadramento com a contabilidade.
 */
export const LC116_COMMON: Array<{ code: string; label: string }> = [
  { code: "1.01", label: "Análise e desenvolvimento de sistemas" },
  { code: "1.02", label: "Programação" },
  { code: "1.03", label: "Processamento, armazenamento ou hospedagem de dados" },
  { code: "1.04", label: "Elaboração de programas de computadores" },
  { code: "1.05", label: "Licenciamento ou cessão de direito de uso de programas de computação" },
  { code: "1.06", label: "Assessoria e consultoria em informática" },
  { code: "1.07", label: "Suporte técnico em informática, instalação, configuração e manutenção de programas" },
  { code: "1.08", label: "Planejamento, confecção, manutenção e atualização de páginas eletrônicas" },
  { code: "3.02", label: "Cessão de direito de uso de marcas e de sinais de propaganda" },
  { code: "6.01", label: "Barbearia, cabeleireiros, manicuros, pedicuros e congêneres" },
  { code: "6.02", label: "Esteticistas, tratamento de pele, depilação e congêneres" },
  { code: "7.10", label: "Limpeza, manutenção e conservação de imóveis, piscinas, jardins e congêneres" },
  { code: "8.02", label: "Instrução, treinamento, orientação pedagógica e educacional" },
  { code: "10.05", label: "Agenciamento, corretagem ou intermediação de bens móveis ou imóveis" },
  { code: "11.01", label: "Guarda e estacionamento de veículos" },
  { code: "13.05", label: "Composição gráfica e confecção de impressos gráficos" },
  { code: "14.01", label: "Lubrificação, limpeza, revisão, conserto e manutenção de máquinas, veículos, aparelhos e equipamentos" },
  { code: "14.02", label: "Assistência técnica" },
  { code: "14.05", label: "Restauração, recondicionamento, pintura, lavagem e beneficiamento de objetos" },
  { code: "14.06", label: "Instalação e montagem de aparelhos, máquinas e equipamentos (ao usuário final)" },
  { code: "14.09", label: "Alfaiataria e costura (material fornecido pelo usuário final)" },
  { code: "14.10", label: "Tinturaria e lavanderia" },
  { code: "14.13", label: "Carpintaria e serralheria" },
  { code: "16.02", label: "Outros serviços de transporte de natureza municipal" },
  { code: "17.01", label: "Assessoria ou consultoria de qualquer natureza" },
  { code: "17.02", label: "Apoio administrativo, digitação, secretaria e congêneres" },
  { code: "17.06", label: "Propaganda e publicidade" },
  { code: "17.12", label: "Administração em geral, inclusive de bens e negócios de terceiros" },
  { code: "17.19", label: "Contabilidade, inclusive serviços técnicos e auxiliares" },
  { code: "17.20", label: "Consultoria e assessoria econômica ou financeira" },
  { code: "23.01", label: "Programação e comunicação visual, desenho industrial e congêneres" },
  { code: "24.01", label: "Chaveiros, carimbos, placas, sinalização visual, banners e adesivos" },
  { code: "26.01", label: "Coleta, remessa ou entrega de correspondências, documentos e objetos" },
];
